In [1]:
import tensorflow as tf
print(tf.__version__)

2023-09-22 21:54:40.493754: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.13.0


# Tensor Introduction

### What is Tensor?
Tensors are multi-dimensional arrays with a uniform type (called a dtype).

### Create Tensors

In [2]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(27, tf.int8)
float = tf.Variable(23.922, tf.float64)
print(string, number, float, sep='\n')

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=27>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=23.922>


### Rank/Degree of Tensors
dimenstion of the matrices

In [3]:
rank0_tensor = tf.constant(1, tf.int8)
rank1_tensor = tf.Variable([1, 2, 3, 4], tf.int8)
rank2_tensor = tf.Variable([[1, 2], [3, 4]], tf.int8)
print("The rank of rank0_tensor is {}".format(tf.rank(rank0_tensor)))
print("The rank of rank1_tensor is {}".format(tf.rank(rank1_tensor)))
print("The rank of rank2_tensor is {}".format(tf.rank(rank2_tensor)))

The rank of rank0_tensor is 0
The rank of rank1_tensor is 1
The rank of rank2_tensor is 2


### Shape of Tensors

In [4]:
rank2_tensor.shape

TensorShape([2, 2])

### Changing Shape

In [5]:
tensor1 = tf.Variable(range(6), tf.int8)
tensor2 = tf.reshape(tensor1, [1, 2, 3])
tensor3 = tf.reshape(tensor1, [3, 2, 1])
tensor4= tf.reshape(tensor1, [3, -1]) # -1 tells tensorflow to calculate the size of the dimension
print(tensor1, tensor2, tensor3, tensor4, sep='\n')

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>
tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]], shape=(3, 2, 1), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)


### Types of Tensors
* Variable
* Constant
* Placeholder
* SparseTensor

Only `Varaible` is mutable.